name: Validate Connector

on:
  push:
    paths:
      - '**'
      - '.github/workflows/validate.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate Power Automate connector structure and required files
      run: |
        chmod +x ./scripts/validate.sh
        ./scripts/validate.sh
